name: Standard checks
on: [push]

jobs:
  build:
    strategy:
      matrix:
        go: ['1.14']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make fmt-check
      - run: make test